debug: false

logging:
  level:
    com.junh.testdata: debug
    org.springframework.web.servlet: debug


spring:
  application.name: test-data
  jpa:
    open-in-view: false
#    JPA? ?? ?? ???? sql??? ???? ??? ??? ?? ?? ?? ??? ????
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # sql ??? ???? ?? ???? ???? ??? ??? ??? ? ??? ?? ?? ????
  sql:
    init:
      mode: always
